In [1]:
import pandas as pd

In [15]:
df_train = pd.read_csv('data/trainReviews.tsv', sep='\t')

In [16]:
df_train.head()

id  category                                               text
0   858         0  burnt money is the perfect festival film    it...
1  1762         1  the   italian hitchcock   and acknowledged mas...
2   235         0  at times   you d think edtv would be an entert...
3   712         0  after a marketing windup of striking visuals a...
4  1319         1  john cusack is the kind of actor who seems to ...

In [17]:
#train_review_df.iloc[1]['text']

In [66]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

In [67]:
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    #('clf', MultinomialNB()),
    #('clf', RandomForestClassifier()),
    ('clf', MLPClassifier())
    ])

In [68]:
text_clf.fit(df_train['text'], df_train['category'])

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MLPClassifier())])

In [69]:
text_clf['vect'].vocabulary_

{'burnt': 2654,
 'money': 12528,
 'is': 10249,
 'the': 19457,
 'perfect': 14105,
 'festival': 7203,
 'film': 7273,
 'it': 10274,
 'will': 21432,
 'show': 17425,
 'once': 13431,
 'or': 13504,
 'twice': 20158,
 'and': 856,
 'then': 19478,
 'no': 13090,
 'one': 13432,
 'thankfully': 19449,
 'ever': 6639,
 'have': 8837,
 'to': 19694,
 'hear': 8898,
 'from': 7793,
 'again': 584,
 'this': 19532,
 'seattle': 17017,
 'international': 10105,
 '2001': 120,
 'emerging': 6260,
 'masters': 11947,
 'series': 17170,
 'easily': 6032,
 'of': 13360,
 'year': 21717,
 'worst': 21613,
 'billed': 1969,
 'as': 1193,
 'gay': 7991,
 'bonnie': 2236,
 'clyde': 3579,
 'gritty': 8487,
 'director': 5387,
 'marcelo': 11848,
 'pi': 14269,
 'eyro': 6930,
 'has': 8802,
 'its': 10283,
 'only': 13440,
 'highlight': 9075,
 'in': 9708,
 'well': 21289,
 'designed': 5138,
 'title': 19688,
 'sequence': 17157,
 'two': 20173,
 'lovers': 11542,
 'get': 8092,
 'involved': 10209,
 'bank': 1582,
 'robbery': 16341,
 'that': 19455,
 

In [70]:
text_clf['tfidf'].idf_

array([6.52146092, 3.88240359, 6.52146092, ..., 6.52146092, 5.82831374,
       6.52146092])

In [71]:
text_clf['clf']

MLPClassifier()

In [72]:
df_test = pd.read_csv('data/testReviews.tsv', sep='\t')

In [73]:
test_predicted = text_clf.predict(df_test['text'])

In [74]:
test_predicted

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,

In [75]:
import numpy as np

In [76]:
np.mean(test_predicted == df_test['category'])

0.792

In [77]:
test_predicted_proba = text_clf.predict_proba(df_test['text'])

In [78]:
test_predicted_proba

array([[0.11817073, 0.88182927],
       [0.88032932, 0.11967068],
       [0.05953625, 0.94046375],
       [0.29043459, 0.70956541],
       [0.10528018, 0.89471982],
       [0.1971474 , 0.8028526 ],
       [0.90073897, 0.09926103],
       [0.22795383, 0.77204617],
       [0.05852654, 0.94147346],
       [0.03713846, 0.96286154],
       [0.04367819, 0.95632181],
       [0.66589567, 0.33410433],
       [0.92849853, 0.07150147],
       [0.04829972, 0.95170028],
       [0.0526908 , 0.9473092 ],
       [0.34584655, 0.65415345],
       [0.11270493, 0.88729507],
       [0.37451216, 0.62548784],
       [0.28559766, 0.71440234],
       [0.47479821, 0.52520179],
       [0.6110382 , 0.3889618 ],
       [0.06775649, 0.93224351],
       [0.6953813 , 0.3046187 ],
       [0.37059148, 0.62940852],
       [0.82104711, 0.17895289],
       [0.42794456, 0.57205544],
       [0.16078201, 0.83921799],
       [0.14303498, 0.85696502],
       [0.95125112, 0.04874888],
       [0.81376648, 0.18623352],
       [0.