In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('reviews.csv', index_col='filename')

In [3]:
df.head(10)

text  \
filename                                                                 
cv439_tok-13632.txt  the farrelly brothers' third film , after dumb...   
cv180_tok-20034.txt  more movie views by jamey hughton at : http : ...   
cv553_tok-13743.txt  if chris farley had strapped some fake mutton-...   
cv026_tok-29622.txt  in zoolander , the world's most successful , i...   
cv126_tok-13691.txt  if the current trends of hollywood filmmaking ...   
cv344_tok-29737.txt  for more reviews and movie trailers , visit ht...   
cv345_tok-9908.txt   director : george armitage cast : john cusack ...   
cv165_tok-11425.txt  written by : peter wang and shirley sunstarrin...   
cv245_tok-19462.txt  if you¹ve been paying attention to the media f...   
cv156_tok-12349.txt  director : john sayles || screenplay : john sa...   

                     review  \
filename                      
cv439_tok-13632.txt       1   
cv180_tok-20034.txt       1   
cv553_tok-13743.txt       1   
cv026_tok-29622.txt       1   
cv126_tok-13691.txt       1   
cv344_tok-29737.txt       1   
cv345_tok-9908.txt        1   
cv165_tok-11425.txt       1   
cv245_tok-19462.txt       1   
cv156_tok-12349.txt       1   

                                                            alpha_text  \
filename                                                                 
cv439_tok-13632.txt  the farrelly brothers  third film   after dumb...   
cv180_tok-20034.txt  more movie views by jamey hughton at   http   ...   
cv553_tok-13743.txt  if chris farley had strapped some fake mutton ...   
cv026_tok-29622.txt  in zoolander   the world s most successful   i...   
cv126_tok-13691.txt  if the current trends of hollywood filmmaking ...   
cv344_tok-29737.txt  for more reviews and movie trailers   visit ht...   
cv345_tok-9908.txt   director   george armitage cast   john cusack ...   
cv165_tok-11425.txt  written by   peter wang and shirley sunstarrin...   
cv245_tok-19462.txt  if you ve been paying attention to the media f...   
cv156_tok-12349.txt  director   john sayles    screenplay   john sa...   

                                                           nostop_text  \
filename                                                                 
cv439_tok-13632.txt  farrelly brothers third film dumb dumber kingp...   
cv180_tok-20034.txt  movie views jamey hughton http welcome movievi...   
cv553_tok-13743.txt  chris farley strapped fake mutton chop sidebur...   
cv026_tok-29622.txt  zoolander world successful influential intelle...   
cv126_tok-13691.txt  current trends hollywood filmmaking continue p...   
cv344_tok-29737.txt  reviews movie trailers visit http www joblo co...   
cv345_tok-9908.txt   director george armitage cast john cusack minn...   
cv165_tok-11425.txt  written peter wang shirley sunstarring peter w...   
cv245_tok-19462.txt  paying attention media frenzy blair witch proj...   
cv156_tok-12349.txt  director john sayles screenplay john sayles st...   

                                                       lemmatized_text  
filename                                                                
cv439_tok-13632.txt  farrelly brother third film dumb dumber kingpi...  
cv180_tok-20034.txt  movie view jamey hughton http welcome movievie...  
cv553_tok-13743.txt  chris farley strapped fake mutton chop sidebur...  
cv026_tok-29622.txt  zoolander world successful influential intelle...  
cv126_tok-13691.txt  current trend hollywood filmmaking continue pr...  
cv344_tok-29737.txt  review movie trailer visit http www joblo com ...  
cv345_tok-9908.txt   director george armitage cast john cusack minn...  
cv165_tok-11425.txt  written peter wang shirley sunstarring peter w...  
cv245_tok-19462.txt  paying attention medium frenzy blair witch pro...  
cv156_tok-12349.txt  director john sayles screenplay john sayles st...

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
df_train, df_test = train_test_split(df, test_size=0.5)

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_recall_fscore_support as score

In [7]:
text_clf = Pipeline([
    ('vect', CountVectorizer(ngram_range=(1,1))),
    ('tfidf', TfidfTransformer()),
    ('clf', RandomForestClassifier())
    ])

In [8]:
text_type = 'lemmatized_text'

In [9]:
text_clf.fit(df_train[text_type], df_train['review'])

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', RandomForestClassifier())])

In [10]:
text_clf['vect'].get_feature_names()[100:110]

['acceptance',
 'accepted',
 'accepting',
 'acception',
 'accepts',
 'access',
 'accessibility',
 'accessible',
 'accident',
 'accidental']

In [11]:
len(text_clf['vect'].get_feature_names())

22639

In [12]:
text_clf['tfidf'].idf_

array([5.46303042, 6.84932478, 6.84932478, ..., 6.84932478, 5.75071249,
       6.84932478])

In [13]:
text_clf['clf']

RandomForestClassifier()

In [14]:
text_clf['clf'].feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
feature_df = pd.DataFrame({"feature": text_clf['vect'].get_feature_names(), 
                           'importance': text_clf['clf'].feature_importances_})

In [16]:
features_sorted = feature_df.sort_values(by=['importance'], ascending=False)

In [17]:
pd.set_option("max_rows", None)
features_sorted.head(100)

feature  importance
1386            bad    0.006555
2201         boring    0.003712
14771   performance    0.003483
12174          make    0.003091
19593      supposed    0.003029
22319   wonderfully    0.002917
539            also    0.002824
12452      material    0.002811
22034          well    0.002729
21911        wasted    0.002718
12510         maybe    0.002646
8687          great    0.002621
13244         movie    0.002607
22386         worst    0.002554
8328            get    0.002365
12908        minute    0.002300
19376        stupid    0.002274
18220        simple    0.002269
6256      effective    0.002211
6830           even    0.002200
11783        little    0.002177
9826           idea    0.002124
5472       director    0.002098
7445           film    0.002094
20738          true    0.002012
10839          john    0.001956
22391         would    0.001901
7187         family    0.001887
16805        review    0.001863
1186        attempt    0.001851
7985         friend    0.001819
11412     laughable    0.001810
11489         least    0.001793
16176        really    0.001782
10850          joke    0.001764
6898      excellent    0.001730
15120          plot    0.001725
20760           try    0.001711
17038         roger    0.001686
11467        leader    0.001682
16902    ridiculous    0.001677
12740          mess    0.001669
16449  relationship    0.001642
9667           http    0.001622
17614        script    0.001620
21861          want    0.001617
11282          lack    0.001611
8532           good    0.001594
15955         quite    0.001585
21944           way    0.001583
8062            fun    0.001576
20188         thing    0.001567
21921      watching    0.001535
22427        writer    0.001534
1807           best    0.001520
20820            tv    0.001519
2853            car    0.001498
4320          could    0.001497
19219         story    0.001472
7456     filmmaking    0.001471
6045            due    0.001469
15240        poorly    0.001457
15401   predictable    0.001435
22308         woman    0.001410
20409           tom    0.001389
1325          awful    0.001386
20093      terrible    0.001385
22381         worse    0.001381
12788       michael    0.001370
3130         change    0.001354
8396           give    0.001353
1969          bland    0.001337
14207         oscar    0.001323
3149      character    0.001322
8471             go    0.001307
3843        complex    0.001305
195        actually    0.001296
11659          life    0.001296
12509           may    0.001290
3201          cheap    0.001279
11880          look    0.001273
4350         couple    0.001271
1681          begin    0.001255
15486        pretty    0.001247
4470         credit    0.001245
22076      whatever    0.001245
11514          left    0.001241
16919         right    0.001236
17840           set    0.001233
17704           see    0.001231
4682            cut    0.001226
11686          like    0.001212
797        anything    0.001179
13800       nothing    0.001162
13077        moment    0.001160
4359         course    0.001145
6296         either    0.001142
11201          know    0.001142
5265         detail    0.001134
17799        sequel    0.001126

In [35]:
# you can do this to see the word distribution vector, but with this much data, you might not want to...
#X_train = text_clf['vect'].fit_transform(df['alpha_text'])
#print(X_train[:100])

In [19]:
len(features_sorted)

22639

In [20]:
y_pred = text_clf.predict(df_test[text_type])

In [21]:
#y_pred

In [22]:
precision, recall, fscore, train_support = score(df_test['review'], y_pred, pos_label=1, average='binary')
print('Precision: {} / Recall: {} / Accuracy: {}'.format(
    round(precision, 3), round(recall, 3), round((y_pred==df_test['review']).sum()/len(y_pred), 3)))

Precision: 0.872 / Recall: 0.584 / Accuracy: 0.737


In [23]:
# my results for multiple runs
# body_text - Precision: 0.735 / Recall: 0.742 / Accuracy: 0.745
# alpha_text - Precision: 0.788 / Recall: 0.65 / Accuracy: 0.74
# nostop_text - Precision: 0.799 / Recall: 0.704 / Accuracy: 0.76
# lemmatized_text - Precision: 0.81 / Recall: 0.67 / Accuracy: 0.753

In [24]:
df_test['pred'] = y_pred

/var/folders/wp/8493czf93l34d7c5ky14j7pr0000gp/T/ipykernel_45535/741341567.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['pred'] = y_pred


In [25]:
y_proba = text_clf.predict_proba(df_test[text_type])

In [26]:
y_proba

array([[0.76, 0.24],
       [0.57, 0.43],
       [0.4 , 0.6 ],
       ...,
       [0.49, 0.51],
       [0.65, 0.35],
       [0.5 , 0.5 ]])

In [27]:
pos_proba = [item[1] for item in y_proba]

In [28]:
#pos_proba

In [29]:
df_test['proba'] = pos_proba

/var/folders/wp/8493czf93l34d7c5ky14j7pr0000gp/T/ipykernel_45535/1857758418.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['proba'] = pos_proba


In [30]:
df_test

text  \
filename                                                                 
cv495_tok-18551.txt  for more reviews and movie screensavers , visi...   
cv675_tok-11864.txt  capsule : perversely entertaining hong kong ac...   
cv506_tok-13396.txt  moon over parador ( 1988 ) 1/4 . produced and ...   
cv257_tok-10937.txt  capsule : a love story hidden inside a half-se...   
cv363_tok-21128.txt  cast : john saxon , ronee blakley , heather la...   
cv487_tok-11827.txt  director : harold becker screenwriter : lawren...   
cv332_tok-11084.txt  slavery is bad . after hundreds of years , we'...   
cv584_tok-14395.txt  release date : september 11 , 1998 starring : ...   
cv448_tok-10768.txt  seen on 31 december 1997 with tony for free at...   
cv671_tok-10077.txt  a miramax pictures release . starring robin wi...   
cv155_tok-13650.txt  starring : tom hanks , tom sizemore , edward b...   
cv300_tok-19831.txt  all those who were offended by there's somethi...   
cv132_tok-29083.txt  for more reviews and movie wallpapers , visit ...   
cv548_tok-11094.txt  member of the internet movie critic's associat...   
cv644_tok-16844.txt  the " fab 4 " of ronald reagan high are four s...   
cv510_tok-29540.txt  the most amazing thing about paul cox's innoce...   
cv249_tok-15275.txt  " i still know what you did last summer " our ...   
cv654_tok-17990.txt  on re-watching italian writer/director dario a...   
cv655_tok-20022.txt  " doesn't it bother you that people like cathe...   
cv105_tok-10942.txt  capsule : another great piece of nonsense from...   
cv123_tok-22269.txt  filmcritic . com presents a review from staff ...   
cv534_tok-12128.txt  my giant is two movies for the price of one , ...   
cv186_tok-28009.txt  to watch a steven seagal film , one must fully...   
cv117_tok-10247.txt  cast : leslie nielsen , kelly lynch , ernie hu...   
cv063_tok-28706.txt  spy kids ( 2001 ) antonio banderas , carla gug...   
cv044_tok-13701.txt  in the first death wish movie , mild-mannered ...   
cv186_tok-7085.txt   the grandfather of italian horror the late mar...   
cv680_tok-18142.txt  " a dream of dark and troubling things . " -- ...   
cv054_tok-9183.txt   wizards is an animated feature that begins wit...   
cv361_tok-7410.txt   this reviewer is ignorant of what hands were r...   
cv337_tok-12262.txt  much ado about nothing . ah , how sweet the ir...   
cv392_tok-5009.txt   driving miss daisy takes its sweet time to tel...   
cv055_tok-24153.txt  starring-david arquette , scott caan , oliver ...   
cv133_tok-15652.txt  directed by jonathan frakes . cast : patrick s...   
cv541_tok-15782.txt  starring the voices of : val kilmer and ralph ...   
cv074_tok-11857.txt  written by stephen peters . directed by john m...   
cv187_tok-12009.txt  nosferatu : the first vampire   -by bill chamb...   
cv244_tok-22147.txt   deuce bigalow male gigolo is a very pointed f...   
cv448_tok-25113.txt  directed by peter lord and nick park . screenp...   
cv174_tok-19826.txt  for more reviews and movie screensavers , visi...   
cv633_tok-14245.txt  renowned hong kong action director tsui hark f...   
cv410_tok-5090.txt   this is the movie that could single-handedly b...   
cv407_tok-17378.txt  during the making of his film-biography of jaz...   
cv623_tok-17930.txt  one of the indicator of badness in film is the...   
cv567_tok-29658.txt  naomi watts chases hollywood dreams along mulh...   
cv158_tok-6654.txt   written by : john herzfeld directed by : john ...   
cv063_tok-10848.txt  deceiver is a plot twist in search of a movie ...   
cv424_tok-29318.txt  summer catch ( 2001 ) . starring freddie prinz...   
cv066_tok-21119.txt  rated r for strong language , crude sexual hum...   
cv051_tok-21020.txt  rated r for intense violence , sexuality and s...   
cv357_tok-10343.txt  one fun activity for parents during the holida...   
cv085_tok-10481.txt  with storytelling this compelling , who needs ...   
cv689_tok-12427.txt  united states , 1998 u . s . release date : 5/...

In [31]:
# let's try: https://www.rogerebert.com/reviews/marmaduke-2010
document_text = """its not especially good but it isnt especially bad either"""
#document_text = """movie was bad acting was poor script was terrible plot was trite"""
#document_text = """movie was great acting was excellent script was magnificent and wonderful plot was exciting"""

In [32]:
text_clf.predict_proba([document_text])

array([[0.61, 0.39]])