In [1]:
reviews = ['excellent film, excellent acting, well written screenplay, coherent plot',
    'mediocre film, unconvincing acting, stilted dialog, incoherent plot']
sentiments = [1, 0]

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'review': reviews, 'sentiment': sentiments})

In [4]:
df

review  sentiment
0  excellent film, excellent acting, well written...          1
1  mediocre film, unconvincing acting, stilted di...          0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
vectorizer = CountVectorizer()

In [7]:
X_train = vectorizer.fit_transform(df['review'])

In [8]:
vectorizer.get_feature_names()

['acting',
 'coherent',
 'dialog',
 'excellent',
 'film',
 'incoherent',
 'mediocre',
 'plot',
 'screenplay',
 'stilted',
 'unconvincing',
 'well',
 'written']

In [9]:
X_train

<2x13 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [10]:
X_train.todense()

matrix([[1, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1],
        [1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0]], dtype=int64)

In [11]:
print(X_train)

  (0, 7)	1
  (0, 1)	1
  (0, 8)	1
  (0, 12)	1
  (0, 11)	1
  (0, 0)	1
  (0, 4)	1
  (0, 3)	2
  (1, 5)	1
  (1, 2)	1
  (1, 9)	1
  (1, 10)	1
  (1, 6)	1
  (1, 7)	1
  (1, 0)	1
  (1, 4)	1


In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
clf = RandomForestClassifier().fit(X_train, df['sentiment'])

In [14]:
positive_review = "excellent film, acting was so so by but the plot was well thought out"

In [15]:
negative_review = "mediocre acting, everything about this was unconvincing, save your money"

In [16]:
positive_vector = vectorizer.transform([positive_review])

In [17]:
positive_vector.todense()

matrix([[1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0]])

In [18]:
negative_vector = vectorizer.transform([negative_review])

In [19]:
negative_vector.todense()

matrix([[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]])

In [20]:
df_results = pd.DataFrame({'word': vectorizer.get_feature_names(), 
              'positive': positive_vector.todense().tolist()[0],
              'negative': negative_vector.todense().tolist()[0]})

In [21]:
df_results

word  positive  negative
0         acting         1         1
1       coherent         0         0
2         dialog         0         0
3      excellent         1         0
4           film         1         0
5     incoherent         0         0
6       mediocre         0         1
7           plot         1         0
8     screenplay         0         0
9        stilted         0         0
10  unconvincing         0         1
11          well         1         0
12       written         0         0

In [22]:
clf.predict(positive_vector)

array([1])

In [23]:
clf.predict(negative_vector)

array([0])

In [24]:
clf.predict_proba(positive_vector)

array([[0.41, 0.59]])

In [25]:
clf.predict_proba(negative_vector)

array([[0.63, 0.37]])